name: TESTING

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate HTML files (optional)
      uses: Cyb3r-Jak3/html-validator-action@v1
      with:
        directory: ./ # or specify a subfolder if your HTML is in one

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Set PHP version you use

    - name: Validate PHP syntax
      run: |
        find . -name "*.php" -exec php -l {} \;

    - name: Run PHP tests (optional)
      if: false # set to true if you later add PHPUnit tests
      run: |
        ./vendor/bin/phpunit